# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: windows-latest

steps:
  - task: NuGetAuthenticate@1
    inputs:
      feedUrl: "https://pkgs.dev.azure.com/tcsnlps/ssc-set/_packaging/tcsnlps-ssc-set-psmod-dev-feed/nuget/v3/index.json"

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Install-Module Microsoft.PowerShell.PSResourceGet -Repository PSGallery -Force
        # Import-Module Microsoft.PowerShell.Security
        Import-Module Microsoft.PowerShell.PSResourceGet 
        
        Get-ChildItem $(Build.SourcesDirectory)

        Publish-PSResource -Path $(packagePath) -Repository $(publishFeed) -ApiKey 123      src\PSRule.Rules.AzureDevOps