# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: windows-latest

steps:
  # - task: NuGetAuthenticate@1
  #   inputs:
  #     feedUrl: "https://pkgs.dev.azure.com/tcsnlps/ssc-set/_packaging/tcsnlps-ssc-set-psmod-dev-feed/nuget/v3/index.json"

  # - task: PowerShell@2
  #   inputs:
  #     targetType: "inline"
  #     script: |

  - powershell: |
      $patToken = $(patToken) | ConvertTo-SecureString -AsPlainText -Force
      $myCredentialsObject = New-Object System.Management.Automation.PSCredential($(patUser), $patToken)

      Register-PSRepository -Name "PSGalleryUpstream" -SourceLocation "https://pkgs.dev.azure.com/tcsnlps/ssc-set/_packaging/tcsnlps-ssc-set-psmod-dev-feed/nuget/v2" -PublishLocation "https://pkgs.dev.azure.com/tcsnlps/ssc-set/_packaging/tcsnlps-ssc-set-psmod-dev-feed/nuget/v2" -InstallationPolicy Trusted -Credential $myCredentialsObject

      Install-Module Microsoft.PowerShell.PSResourceGet -Repository PSGallery -Force
      # Import-Module Microsoft.PowerShell.Security
      Import-Module Microsoft.PowerShell.PSResourceGet 

      Write-Host $(packagePath)
      Write-Host $(publishFeed)

      Get-ChildItem $(Build.SourcesDirectory) -Recurse

      Publish-PSResource -Path $(packagePath) -Repository $(publishFeed) -ApiKey 123
