# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool: default

steps:
  - task: NuGetAuthenticate@1
    inputs:
      feedUrl: "https://pkgs.dev.azure.com/tcsnlps/ssc-set/_packaging/tcsnlps-ssc-set-psmod-dev-feed/nuget/v3/index.json"

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Install-Module Microsoft.PowerShell.PSResourceGet -Repository PSGallery -Force
        Import-Module Microsoft.PowerShell.PSResourceGet 
        
        Publish-PSResource -Path $packagetPath -Repository $(publishFeed) -ApiKey 123      