name: Publish-PSRule.Rules.AzureDevOps

variables:
  - group: "azdo-psrule-run"
  - name: MODULE_SCOPE
    value: "CurrentUser"

trigger:
  - main

pool:
  vmImage: "windows-latest"

steps:
  - task: PowerShell@2
    displayName: "Install prerequisite modules"
    inputs:
      targetType: inline
      pwsh: true
      script: |
        Write-Host "##[group]Installing required PowerShell modules"
        $modules = @(
          'Microsoft.PowerShell.SecretManagement'
          'Microsoft.PowerShell.SecretStore'
          'Microsoft.PowerShell.PSResourceGet'
        )
        foreach ($mod in $modules) {
          if (-not (Get-Module -ListAvailable -Name $mod)) {
            Install-Module -Name $mod `
                           -Scope $env:MODULE_SCOPE `
                           -Force `
                           -AllowClobber `
                           -ErrorAction Stop `
                           -Repository PSGallery
          }
        }
        Write-Host "##[endgroup]"

  - task: PowerShell@2
    displayName: "Register Azure Artifacts Feed"
    inputs:
      targetType: inline
      pwsh: true
      script: |
        . "$(Build.SourcesDirectory)\src\helper-functions\AzureDevOps.ArtifactFeedManagement.ps1"

        $artifactFeed = @{
            Organization = $env:ADO_ORGANIZATION
            Project      = $env:ADO_PROJECT
            FeedName         = $env:ADO_FEED_NAME
            PatUser          = $env:ADO_USERNAME
            PatToken         = (ConvertTo-SecureString -String $env:ADO_PAT -AsPlainText -Force)
            PSRepositoryName = $env:ADO_FEED_NAME
        }

        Register-AzureDevOpsArtifactFeed @artifactFeed
    env:
      ADO_ORGANIZATION: $(azureDevOpsArtifactOrganizationName)
      ADO_PROJECT: $(azureDevOpsArtifactProjectName)
      ADO_FEED_NAME: $(azureDevOpsArtifactProjectNameFeedName)
      ADO_USERNAME: $(azureDevOpsArtifactPatUser)
      ADO_PAT: $(azureDevOpsArtifactPatToken)

  - task: PowerShell@2
    displayName: "Publish PSModule to Azure Artifacts"
    inputs:
      targetType: inline
      pwsh: true
      script: |
        . "$(Build.SourcesDirectory)\src\helper-functions\AzureDevOps.ArtifactFeedManagement.ps1"

        $publishParams = @{
          PatUser           = $env:ADO_USERNAME
          PatToken          = (ConvertTo-SecureString -String $env:ADO_PAT -AsPlainText -Force)
          PSRepositoryName  = $env:ADO_FEED_NAME
          ApiKey            = $env:MODULE_API_KEY
          PackagePath       = '$(Build.SourcesDirectory)\src\PSRule.Rules.AzureDevOps'
        }

        Publish-AzureDevOpsArtifactPackage @publishParams
    env:
      ADO_ORGANIZATION: $(azureDevOpsArtifactOrganizationName)
      ADO_PROJECT: $(azureDevOpsArtifactProjectName)
      ADO_FEED_NAME: $(azureDevOpsArtifactProjectNameFeedName)
      ADO_USERNAME: $(azureDevOpsArtifactPatUser)
      ADO_PAT: $(azureDevOpsArtifactPatToken)
      MODULE_API_KEY: $(psrule-rules-azuredevops-apikey)
