name: Publish-PSRule.Rules.AzureDevOps

variables:
  - group: "azdo-psrule-run"
  - name: MODULE_SCOPE
    value: "CurrentUser"

# # schedules:
# #   - cron: "5 8 * * 0"
# #     displayName: Run every Sunday
# #     branches:
# #       include:
# #         - "*"

trigger:
  - main
  - users/wcamargo/*

pool:
  vmImage: "windows-latest"

steps:
  - task: PowerShell@2
    displayName: "Install prerequisite modules"
    inputs:
      targetType: inline
      pwsh: true
      script: |
        Write-Host "##[group]Installing required PowerShell modules"
        $modules = @(
          'Microsoft.PowerShell.SecretManagement'
          'Microsoft.PowerShell.SecretStore'
          'Microsoft.PowerShell.PSResourceGet'
        )
        foreach ($mod in $modules) {
          if (-not (Get-Module -ListAvailable -Name $mod)) {
            Install-Module -Name $mod `
                           -Scope $env:MODULE_SCOPE `
                           -Force `
                           -AllowClobber `
                           -ErrorAction Stop
          }
        }
        Write-Host "##[endgroup]"

  - task: PowerShell@2
    displayName: "Install PSGallery Powershell Modules Inline"
    inputs:
      # Inline call to the script is being used as is is not possible to escape the '@' in PatUser variable via script
      targetType: inline
      pwsh: true
      script: |
        $ArtifactFeed = @{
          OrganizationName = '$(azureDevOpsArtifactOrganizationName)'
          ProjectName = '$(azureDevOpsArtifactProjectName)'
          FeedName = '$(azureDevOpsArtifactProjectNameFeedName)'
          PatUser = '$(azureDevOpsArtifactPatUser)'
          PatToken = '$(azureDevOpsArtifactPatToken)'
          CustomModules = @('PSRule.Rules.AzureDevOps')
        }

        . "$(Pipeline.Workspace)/s/src/helper-functions\Initialize-ArtifactFeed.ps1" @ArtifactFeed

  - task: PowerShell@2
    displayName: "Publish PSModule to Azure Artifacts"
    inputs:
      targetType: inline
      pwsh: true
      script: |
        # . "$(Build.SourcesDirectory)\src\helper-functions\AzureDevOps.ArtifactFeedManagement.ps1"
        # $artifactFeed = @{
        #     Organization = $env:ADO_ORGANIZATION
        #     Project      = $env:ADO_PROJECT
        #     FeedName         = $env:ADO_FEED_NAME
        #     PatUser          = $env:ADO_USERNAME
        #     PatToken         = (ConvertTo-SecureString -String $env:ADO_PAT -AsPlainText -Force)
        # }

        # Register-AzureDevOpsArtifactFeed @artifactFeed

        . "$(Build.SourcesDirectory)\src\helper-functions\AzureDevOps.ArtifactFeedManagement.ps1"
        $publishParams = @{
          FeedName       = $env:ADO_FEED_NAME
          Username       = $env:ADO_USERNAME
          ApiKey         = '123456'
          PatToken       = (ConvertTo-SecureString -String $env:ADO_PAT -AsPlainText -Force)
          PackagePath    = '$(Build.SourcesDirectory)\src\PSRule.Rules.AzureDevOps'
        }

        Publish-AzureDevOpsArtifactPackage @publishParams
    env:
      ADO_ORGANIZATION: $(azureDevOpsArtifactOrganizationName)
      ADO_PROJECT: $(azureDevOpsArtifactProjectName)
      ADO_FEED_NAME: $(azureDevOpsArtifactProjectNameFeedName)
      ADO_USERNAME: $(azureDevOpsArtifactPatUser)
      ADO_PAT: $(azureDevOpsArtifactPatToken)

  # - task: PowerShell@2
  #   displayName: "Publish PSModule to Azure Artifacts"
  #   inputs:
  #     targetType: inline
  #     pwsh: true
  #     script: |

  #   env:
  #     ADO_ORGANIZATION: $(azureDevOpsArtifactOrganizationName)
  #     ADO_PROJECT: $(azureDevOpsArtifactProjectName)
  #     ADO_FEED_NAME: $(azureDevOpsArtifactProjectNameFeedName)
  #     ADO_API_KEY: $(azureDevOpsArtifactPatToken)
  #     ADO_USERNAME: $(azureDevOpsArtifactPatUser)
  #     ADO_PAT: $(azureDevOpsArtifactPatToken)
