name: Publish-PSRule.Rules.AzureDevOps

variables:
  - group: "azdo-psrule-run"
  - name: MODULE_SCOPE
    value: "CurrentUser"

# # schedules:
# #   - cron: "5 8 * * 0"
# #     displayName: Run every Sunday
# #     branches:
# #       include:
# #         - "*"

trigger:
  - main

pool:
  vmImage: "windows-latest"

steps:
  - task: PowerShell@2
    displayName: "Install prerequisite modules"
    inputs:
      pwsh: true
      script: |
        Write-Host "##[group]Installing required PowerShell modules"
        $modules = @(
          'Microsoft.PowerShell.SecretManagement'
          'Microsoft.PowerShell.SecretStore'
          'Microsoft.PowerShell.PSResourceGet'
        )
        foreach ($mod in $modules) {
          if (-not (Get-Module -ListAvailable -Name $mod)) {
            Install-Module -Name $mod `
                           -Scope $env:MODULE_SCOPE `
                           -Force `
                           -AllowClobber `
                           -ErrorAction Stop
          }
        }
        Write-Host "##[endgroup]"

  - task: PowerShell@2
    displayName: "Load helper functions"
    inputs:
      pwsh: true
      script: |
        # Dot-source so that Register-AzureDevOpsArtifactFeed and Publish-* are available
        . "$(Build.SourcesDirectory)\src\helper-functions\AzureDevOps.ArtifactFeedManagement.ps1"

  - task: PowerShell@2
    displayName: "Initialize Azure DevOps Artifact Feed"
    inputs:
      pwsh: true
      script: |
        $ArtifactFeed = @{
            Organization = $env:ADO_ORGANIZATION
            Project      = $env:ADO_PROJECT
            FeedName         = $env:ADO_FEED_NAME
            PatUser          = $env:ADO_USERNAME
            PatToken         = (ConvertTo-SecureString -String $env:ADO_PAT -AsPlainText -Force)
        }

        Register-AzureDevOpsArtifactFeed @params
    env:
      ADO_ORGANIZATION: $(azureDevOpsArtifactOrganizationName)
      ADO_PROJECT: $(azureDevOpsArtifactProjectName)
      ADO_FEED_NAME: $(azureDevOpsArtifactProjectNameFeedName)
      ADO_USERNAME: $(azureDevOpsArtifactPatUser)
      ADO_PAT: $(azureDevOpsArtifactPatToken)

  - task: PowerShell@2
    displayName: "Publish PSModule to Azure Artifacts"
    inputs:
      pwsh: true
      script: |
        $publishParams = @{
          Organization   = $env:ADO_ORGANIZATION
          Project        = $env:ADO_PROJECT
          FeedName       = $env:ADO_FEED_NAME
          Username       = $env:ADO_USERNAME
          ApiKey         = $env:ADO_API_KEY
          RepositoryName = "PSUpstream"
          PatToken       = (ConvertTo-SecureString -String $env:ADO_PAT -AsPlainText -Force)
          PackagePath    = '$(Build.SourcesDirectory)\src\PSRule.Rules.AzureDevOps'
        }

        Publish-AzureDevOpsArtifactPackage @publishParams
    env:
      ADO_ORGANIZATION: $(azureDevOpsArtifactOrganizationName)
      ADO_PROJECT: $(azureDevOpsArtifactProjectName)
      ADO_FEED_NAME: $(azureDevOpsArtifactProjectNameFeedName)
      ADO_API_KEY: $(azureDevOpsArtifactPatToken)
      ADO_USERNAME: $(azureDevOpsArtifactPatUser)
      ADO_PAT: $(azureDevOpsArtifactPatToken)
